name: portfolioflutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  rive: ^0.13.20
  http: ^1.1.0
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^11.0.0
  flutter_animate: ^4.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/
  - .env
  - assets/characters/Gorgon_1/
  - assets/characters/Gorgon_2/
  - assets/characters/Gorgon_3/
  - assets/characters/Karasu_tengu/
  - assets/characters/Kitsune/
  - assets/characters/Kunoichi/
  - assets/characters/Onre/
  - assets/characters/Satyr_1/
  - assets/characters/Satyr_2/
  - assets/characters/Satyr_3/
  - assets/characters/Yamabushi_tengu/
  - assets/characters/Yurei/
