name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # set your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v22
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}   # set in GitHub Secrets
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # set in GitHub Secrets
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # set in GitHub Secrets
          working-directory: ./build/web
          prod: true
